-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  encryption_events
CREATE TABLE IF NOT EXISTS encryption_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  entity_pk VARCHAR(64) NOT NULL,
  field_name VARCHAR(64) NOT NULL,
  op TEXT NOT NULL,
  policy_id BIGINT NULL,
  local_key_version VARCHAR(64) NULL,
  layers JSONB NULL,
  outcome TEXT NOT NULL,
  error_code VARCHAR(64) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_enc_op CHECK (op IN ('encrypt','decrypt','rotate','rehash','unwrap','wrap')),
  CONSTRAINT chk_enc_outcome CHECK (outcome IN ('success','failure'))
);
